
let texts = [
	'The Moon is a barren, rocky world without air and water. It has dark lava plain on its surface. The Moon is filled wit craters. It has no light of its own. It gets its light from the Sun. The Moo keeps changing its shape as it moves round the Earth. It spins on its axis in 27.3 days stars were named after the Edwin Aldrin were the first ones to set their foot on the Moon on 21 July 1969 They reached the Moon in their space craft named Apollo II.',
	'A snake charmer is a person who moves the streets with different types of the banks of the river Yamuna. It is snakes in his basket. He goes from one place to another to show various types of snakes and their tricks. He carries a pipe with which he plays music and snakes dance to his tune. He usually wears a colourful dress. The job of a snake charmer is quite dangerous. Some snakes are quite poisonous and can even bite him. It is not an easy task to catch and train them for the shows.',
	'The doctor is a person who looks after the sick people and prescribes medicines so that the patient recovers fast. In order to become a doctor, a person has to study medicine. Doctors lead a hard life. Their life is very busy. They get up early in the morning and go to the hospital. They work without taking a break. They always remain polite so that patients feel comfortable with them. Since doctors work so hard we must realise their value.',
	'In a fast-changing world, the fate of the country can be moulded through our ability to harness modern science and technology, which is a road to boost the development programs of the country. Rapid technological advances have reduced the dependency on natural resources or the factors in proportion to it. Man is performing precisely by machines with a regular improvement in his work because of quick technological changes by virtue of scientific advancement all around the world. We have accomplished desired scientific and technological advancement and have succeeded in boosting various important international activities like information and telecommunication, television, meteorological services, medical advancement, industrial development, nuclear research, Space Research Oceanographic Research, etc.',
	'India is an agricultural country. Most of the people live in villages and are farmers. They grow cereals, pulses, vegetables and fruits. The farmers lead a tough life. They get up early in the morning and go to the fields. They stay and work on the farm late till evening. The farmers usually live in kuchcha houses. Though, they work hard they remain poor. Farmers eat simple food; wear simple clothes and rear animals like cows, buffaloes and oxen. Without them there would be no cereals for us to eat. They play an important role in the growth and economy of a country.',
	'City Anti-pollution Drive demands certain steps from all the citi­zens of ABC city. All house-holders should pack the waste in a plastic bag and put the bag in front of their house. The bag will be replaced with an empty bag by the Municipal van every morning. They should maintain the cleanliness of the city. This will make the city pollution free.',
	'A tragedy took place yesterday when a Matador fell into a canal. The driver of the Matador tried to save an auto-rickshaw and lost con­trol on the vehicle. About fifty students were travelling in it. The people from the nearby villages saved twenty-seven students. The dead bod­ies of the drowned were recovered. It was a very painful sight.',
	'I was lucky to escape death by a few seconds. A bomb blasted in the compartment of Nilanchal Express. The overcrowded compartment made me to get down. Anyhow the loss was great. About ten people died and many got injured. It was the job of a terrorist. The government should intensify searching operations in trains.',
	'Reading is a blessing for men and women. The habit of reading introduces us to great masters and great minds. It enables us to pass our time usefully. We avoid bad company and live in a separate world of books. Reading kills boredom in youth and old age.',
	'I eat every fruit. Fruit is good for health. But I like apple most. Apples have many point to score over other fruits. It is tasty. It is juicy. It has more iron. It has more vitamins. It is easily digestible. We can eat this fruit before or after meal. Kashmiri apples are the best to eat.',
	'Rabindranath Tagore is the greatest poet of India. He is also one of the greatest poets of the world. He was born in a rich and cultured family of Kolkata on 7 May 1861. The name of his father was Devendranath Tagore and Sarada Devi was his mother. His grandfather Dwarakanath Tagore was one of the richest men in Kolkata. He did not like going to school. So, he was almost home taught. He went through the epics of the Mahabharata and the Ramayana in his boyhood. He composed his first poem in his early childhood. He touched every branch of Bengali literature. He composed innumerable poems and songs. He also wrote a large number of stories, novels, and essays. His letters are of great literary value. He was awarded the Nobel Prize in literature in 1913 for Geetanjali. He disliked the traditional system of education. So, he set up Santiniketan, Visva Bharati at Bolpur. He was also a great patriot. He gave up Knighthood in protest of Jalianwalah-Bagh-Massacre. He took an active role in the movement against the Partition of Bengal in 1905. He was a man of versatile genius. He died on 7 August 1941. His death created a vacuum in the world of literature.',
	'Unemployment is a burning problem of India today. Our schools and Universities produces more job-seeking men than the jobs avail­able. The young men only want office jobs. They do not get proficiency in some technical line. The result is that our young men roam about on the roads. The incidents of thefts and other unsocial acts are due to unemployment.',
	'The range of History is very wide. There is a history for every subject. Any research on any subject is helped by earlier research. History keeps a record of earlier research. It is not merely a chronicle of the dead past. Past is still living in History. It breaks the limits of time. The range of History is extended from the remote past to the age we live in. It is interesting to everybody. Who does not like to know the history of his village or town or country? Who does not like to know the history of his ancestors or the ancient people of his country? The study of History broadens our outlook. It develops patriotism. It teaches one to love one’s country. History teaches lessons because it repeats itself. History is thus a great teacher. History teaches how to take our present Steppings flawlessly.',
	'Trees are very valuable. They give us shade for the rest. They give shelter to birds and animals. They give us wood to burn. They supply us many necessary things of everyday life They take carbon dioxide from the atmosphere and fill it with oxygen. They cause rains. They check soil erosion. They also check floods. In short the trees are the best friends of man.',
	'Population problem is a major problem of India. There is no in­crease in our resources. But there is a regular increase in our popula­tion. Our roads have more traffic. There are more men on the same land. We will have to make more schools, more hospitals and more essential things for the growing population. If we do not check this prob­lem, poverty will soon overtake us.',
	'Time and tide wait for none. Man has a lot of duties in his short span of life and so time is the most important factor in one’s life. We should remember that we cannot recall the time that is gone. We can stop the clock but we cannot stop the time. If we idle away our time, our appointed work will suffer and success will be hard to achieve. Time lost is lost forever. We must do our work at the earliest opportunity. We must always remember the proverb “A stitch in time saves nine.” What can be done today should not be put off for tomorrow.',
	'Dowry consists of things given by parents to their daughters at the time of their marriage. Once this was done to start life well. But the greedy parents of bridegrooms demand more money and material. Some girls have to lose their lives for bringing fewer dowries. Burning brides is daily news these days. Both the, Government and the public should discourage the dowry seekers.',
	'Drinking stands for drinking of alcohol. There are many evils of drinking. It spoils once health. It affects lungs and other organs of the body. The drunkards drink much and waste their money. They cannot run their families properly. They destroy the live of their family mem­bers. In some cases they also become scoundrels.',
	'An aim is a goal or objective to achieve in life. In order to succeed in life, one must have a goal. My aim in life is to be a teacher. Teaching is a noble and responsible profession. I have come to know that the ever-increasing misery and distress, are due to the ignorance and illiteracy of the people of our country. So I have decided to spread education among the masses as much as possible within my humble power.',
	'Human life is a mixture of weal and woe, smiles and tears. However, once what had seemed to be a memorable day turned out to be the saddest day of my life. We had planned for a picnic with all our classmates after the examination on the bank of the river Ganga. We started early in the morning and reached at 10 am. After the cooking was completed, we wished to take a bath in the Ganga. Our class teacher warned that only those who knew swimming would be allowed to bathe in the river. Rajesh, our youngest classmate, did not know how to swim.',
	'Sometimes we come across some forgetful people in our surroundings. And some geniuses are also forgetful to some extent. We know that Newton boiled his pocket watch instead of an egg. Once Einstein was travelling without a ticket on a train. When the checker demanded the ticket, he was frantically searching for the missing ticket. However, when the checker could recognize him, he assured that the scientist would not have to search for it. Einstein still went on searching and remarked that he was searching to find out where he was going for he totally forgot about his destination.',
	'Early men did not know how to grow food and use fire. Now we are totally dependent on the gifts of Science. Science had made our life easier and more enjoyable with vehicles, TV, radio, telephones, lights, media, computers, etc. Space flight is another wonder of science. Thus through the gifts of science, a man who had once lived in the cave has now landed on the moon.',
	'In recent periods, many campaigns have been organized against employing children in mines, factories, motor garages, restaurants, tea stalls, and shops. There are various households that employ poor children though only a few provide their child servants with adequate food and clothing. They are deprived of education and their wages are paid to their parents and the money is rarely spent on them. It is the extreme poverty of their parents that forces the children to adopt such a profession at a minor age.',
	'Family is the place where you learn your first lesson in life. Your family members are the only assets that will remain with you forever. Whatever the circumstances, family members are always there for each other to support us. Good values and good morals are always taught in a family. In the family, we are prepared to respect our elders and love younger ones. We learn lessons consistently from our family, about honesty, dependability, kindness and so on. Family always provides us with a sensation of so much love and care.',
	'Christmas is one of the most famous and light-hearted festivals which is celebrated across the world by billions of people. People of the Christian religion celebrate Christmas to remember the great works of Jesus Christ. 25th December is celebrated as Christmas Day across the world. Christians celebrate Christmas Day as the birth anniversary of Jesus Christ. Jesus Christ of Bethlehem was a spiritual leader and prophet whose teachings structure the premise of their religion. People follow popular customs including exchanging gifts, decorating Christmas trees, attending church, sharing meals with family and friends and, obviously, trusting that Santa Claus will arrive. 25th December, Christmas Day, has been a federal holiday in the United States since 1870.',
	'The greatest wealth is our own health. A healthy body can earn great wealth but, a wealthy person cannot earn great health. We live in a fast-moving world where individuals have no time for themselves. Most part of their life withers away in search of materialistic wealth in order to outshine others but, along the way, they lose their health. Wealth matters, but, is not as important as health. Spending lots of money on junk food in five-star hotels or on other entertainment sources like watching films for a day and so on has no advantages other than self-satisfaction.',
	'A diet that contains all kinds of necessary ingredients in almost the required quantity is called the “Balanced Diet”. A Balanced diet is one that helps to maintain or improve overall health. We should consume a balanced diet consisting of essential nutrition: liquids, adequate proteins, essential fatty acids, vitamins, minerals, and calories. We must eat fresh fruits, salad, green leafy vegetables, milk, egg, yoghurt, etc. on time in order to maintain a healthy body. Among the minerals, we require chiefly iron, calcium, sodium, potassium, and small quantities of iodine, copper, etc. Milk is perhaps the only single item that can be called a balanced diet in itself.',
	'In recent periods, many campaigns have been organized against employing children in mines, factories, motor garages, restaurants, tea stalls, and shops. There are various households that employ poor children though only a few provide their child servants with adequate food and clothing. They are deprived of education their wages are paid to their parents and the money is rarely spent on them. It is the extreme poverty of their parents that forces the children to adopt such a profession at a minor age. Hence, we need, not only strict laws but also thorough economic reform to reduce the poverty line.',
	'My favourite hobby is gardening. I started it when I was only ten. I dig the land, sow the seeds, and water the plants in my garden. Every afternoon I work for an hour in my garden and watch the buds come up and the branches nod in the breeze. Although a hobby is a source of pleasure and not of profit, my hobby combines the two. My mother looks upon it very kindly, as a part of my garden serves as a kitchen garden. A hobby is an index to a man’s character and I believe my hobby reflects my character.',
	'Trees form an important part of the wealth of a country. Trees supply a country with all the timber necessary for buildings and furniture and provide abundant fuel to the localities nearby. But the greatest use of the trees lies in their power to attract rain and preserve moisture. The leaves of a tree always give off moisture and this constant evaporation cools the surrounding atmosphere. The result is that when the winds laden with moisture blow over a tree, the moisture they carry is condensed and forms clouds that ultimately dissolve in rain. We should stop cutting trees to save the world.',
	'Superstitions and social and religious prejudices give rise to such distressing conditions. We must root out these prejudices and ensure a bright future for the girl children by giving them proper education. Moreover, woman’s rights must be established in social and economic fields.',
	'Of late, sound or noise pollution has adversely affected our normal life in a major way. It is chasing us at almost every step. In schools, colleges, offices, and even hospitals we have an explosion of deafening sound. There are many causes of sound pollution. We are almost deafened by the blaring mikes or the record players which are often played at full volume. Secondly, we have noise pollution caused by impatient automobiles always honking their horns. During some social and religious festivals, crackers are burst indiscriminately. In recent times laws have been passed to take effective steps to control noise pollution.',
	'The newspaper is the mirror of the world. It plays a vital role in modern civilization. In our country newspapers are published in many languages. It helps us to acquire general knowledge. Newspapers provide reports, speeches, reviews on trade and commerce, films, sports, etc, and puzzles. Sometimes it publishes articles written by great scholars. People read newspapers for both profit and pleasure. It brings to the public valuable views, acts of injustice, oppression, and maladministration. It exposes the grievances of the people and criticizes the authorities for their failure. It shapes public opinion. Therefore, freedom of the press should not be barred.',
	'Television is a great gift of science. It offers double the benefits of cinema and radio. Television is the most important and effective instrument of entertainment. It relays live telecasts of important events. It is also the best medium of advertisement. It helps mass education. It plays an important role in the world of sports and games. But it has some demerits. It is used for image building of certain individuals. Some programs are not fit to be seen by the students. There is a risk to be addicted to television. So, studies suffer. It also affects eyesight. So, programs should be carefully selected.',
	'Unity means living and working together. At first, the man was alone in this world. But he found it impossible to live alone. Then the idea of unity came to him because unity is strength. Unity gives us strength. “United we stand, divided we fall.” Unity is needed in a family. A family breaks down for want of unity among the members. A united joint family is the source of happiness. Unity 1s needed for the welfare of society. A man alone in society is weak. Even a strong man cannot protect himself. United effort can give us social security. Unity is very important in our national life. History gives us many examples of the value of unity. We lost our independence for want of unity. We had to divide our country because we were not united. Even at this moment, we are not conscious of the importance of national unity.',
	'The meaning of friendship means a sincere bond between two persons. Man is a social animal. He cannot live alone. So, he needs companions. But a companion cannot be called a friend. A good and true friend should possess some qualities. It is said that a friend in need, is a friend indeed. But we should not seek a friend only when we feel the need. A true friend not only helps us in need but also corrects our faults and shows us the right path. He always stands by us in our difficulties. A friendless man is an object of pity. But true friendship is rare. An open foe is better than a false friend. A true friend is a blessing, a false friend is a curse. A false friend may lead us to the way to hell. So, we should be careful in selecting friends.',
	'Positive thinking is an attitude or mindset characterized by optimism and happiness. A positive person hopes for the best and anticipates success in his life. Although many may scoff at the idea of always being positive, it has a plethora of benefits not only for the mind but also for the body.',
	'Mahatma Gandhi was one of the greatest leaders of the world. He was born on 2 October 1869 at Porbandar in Gujrat. His full name was Mohandas Karamchand Gandhi. After qualifying for the Bar in England he came back to India. Next, he went to South Africa. In South Africa, he first started his non-violent civil disobedience movement against the British Government. In 1914 he returned to India.',


];

texts = Object.freeze(texts);

export default texts;